<a href="https://colab.research.google.com/github/2k177/ML/blob/main/ML_foundation/notebooks/1_linear_algebra_into.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Segment 1: Data Structures for Algebra

###Scalars (Rank 0 Tensors) in Base Python

In [1]:
x = 25
x

25

In [2]:
type(x)

int

In [3]:
y = 3

In [4]:
sum = x+y
sum

28

In [5]:
x_float = 25.0
float_sum = x_float + y
float_sum

28.0

In [6]:
type(float_sum)

float

##Scalars in PyTorch


1. PyTorch and TensorFlow are the two most popular automatic differentiation libraries (a focus of the Calculus I and Calculus II subjects in the ML Foundations series) in Python, itself the most popular programming language in ML
2. PyTorch tensors are designed to be pythonic, i.e., to feel and behave like NumPy arrays
3. The advantage of PyTorch tensors relative to NumPy arrays is that they easily be used for operations on GPU.
4. Documentation on PyTorch tensors, including available data types

In [7]:
import torch

In [11]:
x_pt = torch.tensor(25) #type specification is optional

In [12]:
x_pt

tensor(25)

In [13]:
x_pt = torch.tensor(25, dtype=torch.float16)

In [14]:
x_pt

tensor(25., dtype=torch.float16)

In [16]:
x_pt.shape #no dimention Bcoz scalar tension

torch.Size([])

### Scalars in TensorFlow (version 2.0 or later)

Tensors created with a wrapper, all of which [you can read about here](https://www.tensorflow.org/guide/tensor):  

* `tf.Variable`
* `tf.constant`
* `tf.placeholder`
* `tf.SparseTensor`

Most widely-used is `tf.Variable`, which we'll use here. 

As with TF tensors, in PyTorch we can similarly perform operations, and we can easily convert to and from NumPy arrays

Also, a full list of tensor data types is available [here](https://www.tensorflow.org/api_docs/python/tf/dtypes/DType).

In [18]:
import tensorflow as tf

In [22]:
x_tf = tf.Variable(25, dtype=tf.int16)
x_tf

<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=25>

In [23]:
x_tf.shape

TensorShape([])

In [25]:
y_tf = tf.Variable(3, dtype=tf.int16)

In [26]:
x_tf + y_tf

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [28]:
x_tf + 2 #tf_variable can be operated with common python operation

<tf.Tensor: shape=(), dtype=int16, numpy=27>

In [29]:
tf_sum = tf.add(x_tf, y_tf)
tf_sum

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [32]:
tf_sum.numpy()

28

## Vectors (Rank 1 tensors) in Numpy

In [34]:
import numpy as np

In [35]:
x = np.array([25, 2, 5])
x

array([25,  2,  5])

In [36]:
len(x)

3

In [37]:
x.shape

(3,)

In [38]:
type(x)

numpy.ndarray

In [39]:
x[0]

25

In [40]:
type(x[0])

numpy.int64

## Vector transposition

In [42]:
# Transposing a regular 1-D array has no effect.....:)
x_t = x.T
x_t

array([25,  2,  5])

In [43]:
x_t.shape

(3,)

In [44]:
y = np.array([[12,2,5]])
y

array([[12,  2,  5]])

In [45]:
y.shape

(1, 3)

In [46]:
y_t = y.T
y_t

array([[12],
       [ 2],
       [ 5]])

In [47]:
y_t.shape

(3, 1)

In [48]:
y_t.T

array([[12,  2,  5]])

In [49]:
y_t.T.shape

(1, 3)

## Zero vectors
Have no effect if added to another vector

In [50]:
z= np.zeros(3)
x

array([25,  2,  5])

## Vecor in pytorch and Tensorflow

In [51]:
x_pt = torch.tensor([25,5,3])
x_pt

tensor([25,  5,  3])

In [53]:
x_tf = tf.Variable([25, 2, 5])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  2,  5], dtype=int32)>

# $L^2$  Norm

In [54]:
x

array([25,  2,  5])

In [57]:
(25**2 + 2**2 + 5**2) ** (1/2) #euclidain distance from origin

25.573423705088842

In [58]:
np.linalg.norm(x)

25.573423705088842

##$L^1$ Norm

In [59]:
x

array([25,  2,  5])

In [60]:
np.abs(25) + np.abs(2) + np.abs(5)

32

## Squared $L^2$  norm

In [61]:
x

array([25,  2,  5])

In [62]:
(25**2 + 2**2 + 5**2)

654

In [64]:
np.dot(x,x) #sqauared L2 norm = xT.x

654

## Max norm

In [66]:
x

array([25,  2,  5])

In [67]:
np.max([np.abs(25), np.abs(2), np.abs(5)])

25

## Orthogonal vectors

In [68]:
i = np.array([1, 0])
i

array([1, 0])

In [69]:
j = np.array([0, 1])
j

array([0, 1])

In [70]:
np.dot(i, j)

0